spring:
  cache:
    redis:
      # 设置缓存过期时间 30天，单位为毫秒，默认为 1 小时
      time-to-live: 2592000000
    type: redis
  redis:
    # 使用 1 号库，默认为 0 号库
    database: 1
    host: localhost
    port: 6379
    password: ${REDIS_PASSWORD}
    lettuce:
      pool:
        # 设置连接池中允许的最大连接数（即最大并发连接数），当达到这个数量时，新的请求将会被阻塞直到有可用连接释放出来，负数表示没有限制。
        max-active: 1000
        # 等待空闲连接的最大等待时间，负数表示一直等待
        max-wait: -1ms
        # 设置连接池中最大的空闲连接数。连接池会维护一定数量的空闲连接以提高性能。如果当前空闲连接数超过这个数值，超出的连接将被关闭
        max-idle: 16
        # 设置连接池中最小的空闲连接数。即使在空闲状态下，连接池也会至少保持这个数量的连接，避免频繁创建和销毁连接。
        min-idle: 8